services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./smart-school-bn
    container_name: smart-school-bn
    restart: always
    env_file: ./smart-school-bn/.env
    ports:
      - "3000:3000"
    depends_on:
      - postgres

  frontend:
    build: ./smart-school-fn
    container_name: smart-school-fn
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    env_file:
      - ./smart-school-fn/.env

volumes:
  postgres_data:
